version: '3.7'

services: 
   s_pdb:
      container_name: c_pdb
      image: postgres
      restart: unless-stopped
      ports:
         - '5432:5432'
      environment:
         - POSTGRES_USER=gyuce
         - POSTGRES_PASSWORD=123456
         - POSTGRES_DB=eticaretdb
      volumes:
         - postgres-data:/var/lib/postgresql/data
volumes:
   postgres-data: