version: '3.7'

services: 
   eticaretclient:
      container_name: eticaretclient
      build: 
         context: .
         dockerfile: Dockerfile
      volumes: 
         - '.:/app'
         - '/node_modules:/app/node_modules'
      ports:
         - '4201:4200'