version: '3.7'

services: 
   s_pdb:
      container_name: c_pdb
      image: postgres
      restart: always
      ports:
         - '5432:5432'
      environment:
         - POSTGRES_USER=gyuce
         - POSTGRES_PASSWORD=123456
         - PGDATA=/var/lib/postgresql/data/pgdata
         - POSTGRES_DB=eticaretdb
      volumes:
         - /opt/app_data/postgres:/var/lib/postgresql/data/pgdata